# Generated by Django 5.1.1 on 2024-09-30 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='Call ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20, verbose_name='Status')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
