version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - marriage_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    user: root
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin_sessions:/var/lib/pgadmin/sessions
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - marriage_network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  web:
    container_name: marriage_agency
    build:
      context: .
    networks:
      - marriage_network
    volumes:
      - .:/app
      - ./logs:/logs 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  postgres_data:

networks:
  marriage_network:
