# Generated by Django 5.1.1 on 2024-09-30 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('groom', 'Groom'), ('bride', 'Bride')], max_length=10, verbose_name='User Type')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='Hobbies')),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True, verbose_name='Languages Spoken')),
                ('looking_for', models.TextField(blank=True, null=True, verbose_name='Looking For')),
                ('goals_in_relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Goals in Relationship')),
                ('smoking', models.BooleanField(default=False, verbose_name='Smoking')),
                ('drinking', models.BooleanField(default=False, verbose_name='Drinking')),
                ('children', models.BooleanField(default=False, verbose_name='Children')),
                ('willingness_to_have_children', models.BooleanField(default=False, verbose_name='Willingness to have Children')),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marital Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_level', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Income Level')),
                ('housing_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Housing Status')),
                ('car', models.BooleanField(default=False, verbose_name='Car')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BrideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_children', models.BooleanField(default=False, verbose_name='Has Children')),
                ('education_level', models.CharField(max_length=255, verbose_name='Education Level')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
